import React from 'react';
import { Container, Grid, Typography } from '@mui/material';
import aboutUsPic from '../../../images/banner/2.jfif'
import { width } from '@mui/system';

const AboutUs = () => {
    return (
      <Container>
          <Typography style={{margin:'20px 0',color:'orange'}} variant="h3">
                About Us
            </Typography>
        <Grid container spacing={2}>
        <Grid item xs={12} md={6}>
          <Typography variant="h6" sx={{color:'gray',textAlign:'justify',mx:4}}>
          Custom motorcycle descriptions that are informative, engaging, and contain relevant keywords are the key markers of descriptions that help you boost sales and maximize profits. Motorcycle descriptions which are copied and reproduced from a manufacturer’s website can cost a bike dealer dearly in the search engines. These heavily duplicated descriptions can result in a drastic fall in the page rank of a your website since Google is known for penalizing sites that have a lot of duplicate content. A good motorcycle description must also be easy to ready and make an emotional connection with potential buyers. Verbose and robo-speak comments generated by algorithms can consign an dealership to internet obscurity and ruin its chances of success. At Dealer Assist Now, we have been offering custom Hand Written motorcycle description writing services since 2007. 
          </Typography>
        </Grid>
        <Grid item xs={12} sx={{width:'150px'}} md={6}>
          <img style={{marginRight:'20px',borderRadius:'10px'}} src={aboutUsPic} alt="" />
        </Grid>
      </Grid>
      </Container>
    );
};

export default AboutUs;